
const exercises={
 pushup:{name:'Push-Up',category:'Chest',difficulty:'Beginner',equipment:'Bodyweight',description:'A controlled horizontal pressing movement with a rigid body line.',primary:['Chest','Triceps'],secondary:['Shoulders','Core'],instructions:['Set hands just outside shoulder width.','Brace the core and keep a straight body line.','Lower the chest with elbows controlled.','Press the floor away and return to the top.'],mistakes:['Hips sagging or piking','Elbows flaring excessively','Dropping too quickly','Losing a braced core'],form:['Neutral head and spine','Controlled descent','Stable hands','Full-body tension'],reps:10,sets:3,duration:30},
 bench:{name:'Bench Press',category:'Chest',difficulty:'Intermediate',equipment:'Bench + Barbell',description:'A horizontal press emphasizing the chest while maintaining stable shoulders.',primary:['Chest','Triceps'],secondary:['Shoulders'],instructions:['Set your shoulder blades back on the bench.','Grip the bar evenly and brace your body.','Lower the bar under control toward the chest.','Press upward without losing your setup.'],mistakes:['Bouncing the bar','Unstable wrists','Shoulders rolling forward','Excessive arching'],form:['Stable shoulder blades','Controlled bar path','Firm feet','Wrists stacked'],reps:8,sets:3,duration:30},
 pullup:{name:'Pull-Up',category:'Back',difficulty:'Intermediate',equipment:'Pull-Up Bar',description:'A vertical pulling movement using the upper back and arms.',primary:['Lats','Biceps'],secondary:['Core','Upper Back'],instructions:['Hang with a controlled grip.','Brace the core and set the shoulders.','Pull the elbows toward the ribs.','Lower under control to the start.'],mistakes:['Kipping unintentionally','Shrugging shoulders','Half repetitions','Swinging excessively'],form:['Active shoulders','Controlled body','Elbows drive down','Smooth descent'],reps:6,sets:3,duration:30},
 lat:{name:'Lat Pulldown',category:'Back',difficulty:'Beginner',equipment:'Cable Machine',description:'A seated vertical pull that teaches controlled lat engagement.',primary:['Lats','Biceps'],secondary:['Upper Back','Core'],instructions:['Sit tall and brace your core.','Grip the bar slightly wider than shoulders.','Pull the bar toward the upper chest.','Return slowly without dropping the weight.'],mistakes:['Pulling behind the neck','Leaning too far back','Using momentum','Letting shoulders shrug'],form:['Tall torso','Elbows down','Controlled return','Neutral neck'],reps:10,sets:3,duration:30},
 row:{name:'Dumbbell Row',category:'Back',difficulty:'Beginner',equipment:'Dumbbell',description:'A unilateral pull emphasizing the upper back and lats.',primary:['Lats','Upper Back'],secondary:['Biceps','Core'],instructions:['Brace one hand on a stable surface.','Keep the spine long.','Pull the dumbbell toward the hip.','Lower with control.'],mistakes:['Rotating the torso','Shrugging','Pulling toward the shoulder','Rushing the eccentric'],form:['Stable hips','Long spine','Elbow toward hip','Controlled range'],reps:10,sets:3,duration:30},
 squat:{name:'Squat',category:'Legs',difficulty:'Beginner',equipment:'Bodyweight / Rack',description:'A fundamental lower-body movement emphasizing the quads and glutes.',primary:['Quadriceps','Glutes'],secondary:['Hamstrings','Core'],instructions:['Stand with feet around shoulder width.','Brace the core and keep the chest controlled.','Push the hips back and bend the knees.','Keep knees tracking with the toes.','Drive through the floor to stand tall.'],mistakes:['Knees collapsing inward','Heels lifting','Dropping without control','Excessive spinal rounding'],form:['Neutral spine','Stable feet','Knees track toes','Controlled depth'],reps:12,sets:3,duration:35},
 lunge:{name:'Lunge',category:'Legs',difficulty:'Beginner',equipment:'Bodyweight',description:'A unilateral leg movement for strength, balance and control.',primary:['Quadriceps','Glutes'],secondary:['Hamstrings','Calves'],instructions:['Stand tall with a stable stance.','Step forward and lower under control.','Keep the front knee tracking over the foot.','Push through the front foot to return.'],mistakes:['Front knee collapsing','Very narrow stance','Pushing off the back leg','Losing balance'],form:['Tall torso','Stable front foot','Controlled descent','Balanced return'],reps:8,sets:3,duration:30},
 rdl:{name:'Romanian Deadlift',category:'Legs',difficulty:'Intermediate',equipment:'Dumbbells / Barbell',description:'A hip-hinge movement emphasizing the posterior chain.',primary:['Hamstrings','Glutes'],secondary:['Back','Core'],instructions:['Stand tall with the weight close.','Soften the knees and push the hips back.','Keep the spine long as the torso inclines.','Drive the hips forward to stand.'],mistakes:['Squatting instead of hinging','Rounding the back','Weight drifting away','Overextending at the top'],form:['Long spine','Hips move back','Weight stays close','Controlled hinge'],reps:10,sets:3,duration:35},
 press:{name:'Shoulder Press',category:'Shoulders',difficulty:'Beginner',equipment:'Dumbbells',description:'An overhead press focused on the shoulders with a stable trunk.',primary:['Shoulders'],secondary:['Triceps','Core'],instructions:['Start with weights near shoulder height.','Brace the trunk.','Press overhead smoothly.','Lower the weights under control.'],mistakes:['Overarching the back','Pressing unevenly','Dropping the weights','Shrugging excessively'],form:['Braced core','Smooth press','Neutral wrists','Controlled return'],reps:10,sets:3,duration:30},
 lateral:{name:'Lateral Raise',category:'Shoulders',difficulty:'Beginner',equipment:'Dumbbells',description:'A controlled shoulder isolation movement.',primary:['Side Delts'],secondary:['Upper Traps'],instructions:['Stand tall with light weights.','Keep a soft elbow bend.','Raise arms toward shoulder height.','Lower slowly without swinging.'],mistakes:['Using momentum','Shrugging','Going far above control','Heavy weights'],form:['Soft elbows','No swing','Controlled tempo','Stable torso'],reps:12,sets:3,duration:30},
 curl:{name:'Bicep Curl',category:'Arms',difficulty:'Beginner',equipment:'Dumbbells',description:'An elbow-flexion movement emphasizing the biceps.',primary:['Biceps'],secondary:['Forearms'],instructions:['Stand tall with elbows near the body.','Curl the forearms upward.','Pause briefly near the top.','Lower slowly to full control.'],mistakes:['Swinging the torso','Elbows drifting forward','Dropping quickly','Excessive wrist movement'],form:['Stable elbows','Controlled tempo','Neutral wrists','No momentum'],reps:12,sets:3,duration:30},
 tricep:{name:'Tricep Extension',category:'Arms',difficulty:'Beginner',equipment:'Dumbbell / Cable',description:'An elbow-extension movement emphasizing the triceps.',primary:['Triceps'],secondary:['Shoulders'],instructions:['Set the shoulders and brace the trunk.','Bend the elbows under control.','Extend the elbows without swinging.','Return slowly.'],mistakes:['Elbows flaring','Swinging','Using too much weight','Short range'],form:['Stable shoulders','Elbows controlled','Smooth extension','Controlled return'],reps:12,sets:3,duration:30},
 plank:{name:'Plank',category:'Core',difficulty:'Beginner',equipment:'Bodyweight',description:'An isometric core exercise focused on trunk stability.',primary:['Core'],secondary:['Shoulders','Glutes'],instructions:['Set elbows or hands beneath the shoulders.','Brace the trunk and squeeze the glutes.','Keep a straight line from head to heels.','Breathe steadily while holding.'],mistakes:['Hips sagging','Hips too high','Holding breath','Neck craning'],form:['Neutral neck','Braced core','Level hips','Steady breathing'],reps:30,sets:3,duration:30},
 crunch:{name:'Crunch',category:'Core',difficulty:'Beginner',equipment:'Bodyweight',description:'A controlled trunk-flexion movement for the abdominal wall.',primary:['Abs'],secondary:['Core'],instructions:['Lie comfortably with knees bent.','Brace gently and curl the upper torso.','Keep the movement controlled.','Return without dropping the head.'],mistakes:['Pulling the neck','Using momentum','Very large range','Holding breath'],form:['Neck relaxed','Slow tempo','Ribcage curls','Controlled return'],reps:15,sets:3,duration:30}
};
const categories=['All','Chest','Back','Legs','Shoulders','Arms','Core'];
const state={screen:'home',exercise:'squat',filter:'All',speed:1,angle:'front',playing:false,rep:0,set:1,elapsed:0,sessionStart:0,totalReps:0,totalSets:0,completedExercises:new Set(),timer:null,animStart:0,cycleMs:3200};
const $=id=>document.getElementById(id);function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');state.screen=id}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function buildFilters(){const f=$('filters');f.innerHTML='';categories.forEach(c=>{const b=document.createElement('button');b.className='btn small filter '+(c===state.filter?'active':'');b.textContent=c;b.onclick=()=>{state.filter=c;buildFilters();renderLibrary()};f.appendChild(b)})}
function renderLibrary(){const grid=$('exerciseGrid');grid.innerHTML='';Object.entries(exercises).filter(([_,e])=>state.filter==='All'||e.category===state.filter).forEach(([id,e])=>{const c=document.createElement('article');c.className='card';c.innerHTML=`<div><div class="tag">${e.category}</div><h3>${e.name}</h3><p>${e.description}</p><div class="meta"><span>${e.difficulty}</span><span>${e.equipment}</span></div></div><button class="btn small primary vr-target" data-ex="${id}">Study Exercise</button>`;c.querySelector('button').onclick=()=>openDetail(id);grid.appendChild(c)})}
function openDetail(id){state.exercise=id;const e=exercises[id];$('detailCategory').textContent=`${e.category} · ${e.equipment}`;$('detailName').textContent=e.name;$('detailDescription').textContent=e.description;$('detailReps').textContent=e.reps;$('detailSets').textContent=e.sets;$('detailDiff').textContent=e.difficulty;$('primaryMuscles').innerHTML=e.primary.map(x=>`<span class="muscle">${x}</span>`).join('');$('secondaryMuscles').innerHTML=e.secondary.map(x=>`<span class="muscle secondary">${x}</span>`).join('');$('instructions').innerHTML=e.instructions.map(x=>`<li>${x}</li>`).join('');$('formList').innerHTML=e.form.map(x=>`<li>✓ ${x}</li>`).join('');$('mistakes').innerHTML=e.mistakes.map(x=>`<li>✕ ${x}</li>`).join('');buildCoach(id);show('detail');state.playing=false;updateCoachVisibility()}
function buildCoach(id){const root=$('coach3d');root.innerHTML='';const g=document.createElement('a-entity');g.id='human';g.setAttribute('position','0 0 -3');g.setAttribute('scale','.9 .9 .9');
 const pelvis=document.createElement('a-box');pelvis.id='pelvis';pelvis.setAttribute('position','0 1.35 0');pelvis.setAttribute('width','.65');pelvis.setAttribute('height','.38');pelvis.setAttribute('depth','.35');pelvis.setAttribute('color','#4d6679');g.appendChild(pelvis);
 const torso=document.createElement('a-box');torso.id='torso';torso.setAttribute('position','0 2 0');torso.setAttribute('width','.72');torso.setAttribute('height','1.05');torso.setAttribute('depth','.38');torso.setAttribute('color','#7b9bb2');g.appendChild(torso);
 const head=document.createElement('a-sphere');head.id='head';head.setAttribute('position','0 2.82 0');head.setAttribute('radius','.27');head.setAttribute('color','#d7a77c');g.appendChild(head);
 const parts=[['upperL','-.48 2.2 0','0.18 .65 .18'],['upperR','.48 2.2 0','0.18 .65 .18'],['foreL','-.62 1.72 0','0.16 .6 .16'],['foreR','.62 1.72 0','0.16 .6 .16'],['thighL','-.22 .92 0','0.23 .82 .23'],['thighR','.22 .92 0','0.23 .82 .23'],['shinL','-.22 .25 0','0.19 .7 .19'],['shinR','.22 .25 0','0.19 .7 .19']];parts.forEach(([n,p,dim])=>{const x=document.createElement('a-box');x.id=n;x.setAttribute('position',p);const [w,h,d]=dim.split(' ');x.setAttribute('width',w);x.setAttribute('height',h);x.setAttribute('depth',d);x.setAttribute('color','#6e8da4');g.appendChild(x)});
 if(id==='row'){['L','R'].forEach(side=>{const d=document.createElement('a-cylinder');d.id='dumbbell'+side;d.setAttribute('radius','.09');d.setAttribute('height','.48');d.setAttribute('rotation','0 0 90');d.setAttribute('color','#202832');g.appendChild(d);const w1=document.createElement('a-cylinder');w1.id='plate'+side+'a';w1.setAttribute('radius','.15');w1.setAttribute('height','.07');w1.setAttribute('rotation','0 0 90');w1.setAttribute('color','#111820');g.appendChild(w1);const w2=document.createElement('a-cylinder');w2.id='plate'+side+'b';w2.setAttribute('radius','.15');w2.setAttribute('height','.07');w2.setAttribute('rotation','0 0 90');w2.setAttribute('color','#111820');g.appendChild(w2)})}
 root.appendChild(g);updateMuscleVisual(id);pose(0);}
function updateMuscleVisual(id){const e=exercises[id];const root=$('coach3d');if(root.firstElementChild)root.firstElementChild.setAttribute('data-primary',e.primary.join(','));}
function setPosePart(n,pos,rot){const e=$(n);if(!e)return;e.object3D.position.set(pos[0],pos[1],pos[2]);e.object3D.rotation.set(rot[0],rot[1],rot[2]);}
function pose(t){const id=state.exercise,h=$('human');if(!h)return;const phase=(t%state.cycleMs)/state.cycleMs;const p=Math.sin(phase*Math.PI*2);const down=Math.max(0,-p);const lift=Math.max(0,p);const reset=()=>{h.object3D.position.set(0,0,-3);h.object3D.rotation.set(0,0,0);h.object3D.scale.set(.9,.9,.9);};reset();
 if(id==='pushup'){
   const dip=down*.18; h.object3D.position.set(0,.72,-3.0); h.object3D.rotation.set(0,0,-Math.PI/2);
   setPosePart('pelvis',[0,1.35+dip,0],[0,0,0]);setPosePart('torso',[0,2.0+dip,0],[0,0,0]);setPosePart('head',[0,2.82+dip,0],[0,0,0]);
   setPosePart('upperL',[-.48,2.2+dip,0],[0,0,.15]);setPosePart('upperR',[.48,2.2+dip,0],[0,0,-.15]);setPosePart('foreL',[-.62,1.72+dip,0],[0,0,0]);setPosePart('foreR',[.62,1.72+dip,0],[0,0,0]);
   setPosePart('thighL',[-.22,.92,0],[0,0,0]);setPosePart('thighR',[.22,.92,0],[0,0,0]);setPosePart('shinL',[-.22,.25,0],[0,0,0]);setPosePart('shinR',[.22,.25,0],[0,0,0]);
   if(down>0){h.object3D.position.y-=.16*down;}
 }else if(id==='plank'){
   h.object3D.position.set(0,.55,-3.0);h.object3D.rotation.set(0,0,-Math.PI/2);
   setPosePart('pelvis',[0,1.35,0],[0,0,0]);setPosePart('torso',[0,2,0],[0,0,0]);setPosePart('head',[0,2.82,0],[0,0,0]);
   setPosePart('upperL',[-.48,2.2,0],[0,0,.2]);setPosePart('upperR',[.48,2.2,0],[0,0,-.2]);setPosePart('foreL',[-.62,1.72,0],[0,0,0]);setPosePart('foreR',[.62,1.72,0],[0,0,0]);
   setPosePart('thighL',[-.22,.92,0],[0,0,0]);setPosePart('thighR',[.22,.92,0],[0,0,0]);setPosePart('shinL',[-.22,.25,0],[0,0,0]);setPosePart('shinR',[.22,.25,0],[0,0,0]);
 }else if(id==='row'){
   h.object3D.position.set(0,0,-3);const hinge=.72-down*.12;setPosePart('torso',[0,2,0],[hinge,0,0]);setPosePart('head',[0,2.82,0],[hinge,0,0]);setPosePart('pelvis',[0,1.35,0],[hinge*.35,0,0]);
   setPosePart('thighL',[-.22,.92,0],[-.22,0,0]);setPosePart('thighR',[.22,.92,0],[-.22,0,0]);setPosePart('shinL',[-.22,.25,0],[.12,0,0]);setPosePart('shinR',[.22,.25,0],[.12,0,0]);
   const pull=lift*.55;setPosePart('upperL',[-.48,1.88,.08],[hinge*.35,0,.18-pull]);setPosePart('upperR',[.48,1.88,.08],[hinge*.35,0,-.18+pull]);setPosePart('foreL',[-.62,1.45,.2],[hinge*.15,0,.15-pull]);setPosePart('foreR',[.62,1.45,.2],[hinge*.15,0,-.15+pull]);
   [['dumbbellL',[-.62,1.2,.25]],['dumbbellR',[.62,1.2,.25]],['plateLa',[-.62,1.2,.25]],['plateLb',[-.62,1.2,.25]],['plateRa',[.62,1.2,.25]],['plateRb',[.62,1.2,.25]]].forEach(([n,pos])=>setPosePart(n,pos,[0,0,Math.PI/2]));
 }else if(id==='squat'||id==='lunge'||id==='rdl'){setPosePart('pelvis',[0,1.35-down*.55,0],[0,0,0]);setPosePart('torso',[0,2-down*.35,0],[0,0,0]);setPosePart('head',[0,2.82-down*.35,0],[0,0,0]);setPosePart('thighL',[-.22,.92,0],[0,0,down*.42]);setPosePart('thighR',[.22,.92,0],[0,0,-down*.42]);setPosePart('shinL',[-.22,.25,0],[0,0,-down*.2]);setPosePart('shinR',[.22,.25,0],[0,0,down*.2]);setPosePart('upperL',[-.48,2.2,0],[0,0,down*.25]);setPosePart('upperR',[.48,2.2,0],[0,0,-down*.25]);}
 else if(id==='curl'){setPosePart('foreL',[-.62,1.72,0],[0,0,-lift*.9]);setPosePart('foreR',[.62,1.72,0],[0,0,lift*.9]);}
 else if(id==='press'||id==='lateral'){setPosePart('foreL',[-.62,1.72,0],[0,0,-lift*1]);setPosePart('foreR',[.62,1.72,0],[0,0,lift*1]);setPosePart('upperL',[-.48,2.2,0],[0,0,-lift*.45]);setPosePart('upperR',[.48,2.2,0],[0,0,lift*.45]);}
 else if(id==='bench'||id==='pullup'||id==='lat'||id==='crunch'||id==='tricep'){const amount=down;setPosePart('torso',[0,2,0],[0,0,amount*.08]);setPosePart('upperL',[-.48,2.2,0],[0,0,amount*.7]);setPosePart('upperR',[.48,2.2,0],[0,0,-amount*.7]);setPosePart('foreL',[-.62,1.72,0],[0,0,-amount*.7]);setPosePart('foreR',[.62,1.72,0],[0,0,amount*.7]);}}
let last=performance.now(),lastCycle=-1;function frame(now){const dt=now-last;last=now;if(state.playing){const cycle=Math.floor((state.animStart+dt*state.speed)/state.cycleMs);state.animStart+=dt*state.speed;if(cycle!==lastCycle){if(lastCycle>=0){state.rep++;state.totalReps++;updateWorkout();if(state.rep>=exercises[state.exercise].reps){state.playing=false;completeSet()}}lastCycle=cycle}pose(state.animStart);if($('animProgress'))$('animProgress').style.width=((state.animStart%state.cycleMs)/state.cycleMs*100)+'%'}requestAnimationFrame(frame)}requestAnimationFrame(frame);
function updateCoachVisibility(){const h=$('human');if(h){const a=state.angle;h.setAttribute('rotation',a==='front'?'0 0 0':a==='side'?'0 90 0':'0 35 0')}}
function startExercise(id=state.exercise){state.exercise=id;state.rep=0;state.set=1;state.elapsed=0;state.totalReps=0;state.totalSets=0;state.sessionStart=performance.now();$('wName').textContent=exercises[id].name;$('wTarget').textContent=exercises[id].reps;$('wRep').textContent='0';$('wSet').textContent=`1/${exercises[id].sets}`;show('workout');state.playing=false;state.animStart=0;lastCycle=-1;updateWorkout();if(state.timer)clearInterval(state.timer);state.timer=setInterval(()=>{if(state.playing){state.elapsed++;$('wTime').textContent=formatTime(state.elapsed)}},1000);}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function updateWorkout(){const e=exercises[state.exercise];$('wRep').textContent=state.rep;$('wTarget').textContent=e.reps;$('wSet').textContent=`${state.set}/${e.sets}`;$('wProgress').style.width=Math.min(100,state.rep/e.reps*100)+'%';$('wSpeed').textContent=state.speed+'×';$('wPlay').textContent=state.playing?'Running':'Start'}
function completeSet(){const e=exercises[state.exercise];state.totalSets++;state.completedExercises.add(state.exercise);toast('Set complete — take a short rest.');if(state.set<e.sets){state.set++;state.rep=0;state.animStart=0;lastCycle=-1;updateWorkout()}else{nextExercise()}}
function nextExercise(){const ids=Object.keys(exercises),i=ids.indexOf(state.exercise);const next=ids[(i+1)%ids.length];state.exercise=next;const e=exercises[next];state.rep=0;state.set=1;state.animStart=0;lastCycle=-1;$('wName').textContent=e.name;$('wTarget').textContent=e.reps;$('wSet').textContent=`1/${e.sets}`;toast('Next exercise loaded.');updateWorkout();buildCoach(next)}
function finishWorkout(){if(state.timer)clearInterval(state.timer);state.playing=false;$('sExercises').textContent=Math.max(1,state.completedExercises.size);$('sSets').textContent=state.totalSets;$('sReps').textContent=state.totalReps;$('sDuration').textContent='Duration: '+formatTime(state.elapsed);show('summary')}
function openInfo(title,text){$('modalTitle').textContent=title;$('modalText').textContent=text;$('infoModal').classList.add('show')}function vrIndex(){return ['squat','pushup','row','plank'].filter(id=>exercises[id]);}
function updateVrMenu(){const e=exercises[state.exercise];$('vrMenuExercise').setAttribute('value',`Exercise: ${e.name}`);$('vrMenuStartText').setAttribute('value',state.playing?'RUNNING':'START');$('vrMenuPauseText').setAttribute('value',state.playing?'PAUSE':'RESUME');}
function setVrMenuVisible(v){$('vrMenuRoot').setAttribute('visible',v);updateVrMenu();}
function vrSelect(id){if(!exercises[id])return;state.exercise=id;buildCoach(id);if(state.screen==='workout'){const e=exercises[id];$('wName').textContent=e.name;$('wTarget').textContent=e.reps;$('wSet').textContent=`1/${e.sets}`;state.rep=0;state.set=1;state.animStart=0;lastCycle=-1;updateWorkout();}updateVrMenu();toast(`${exercises[id].name} selected`);}
function vrStart(){if(state.screen!=='workout')startExercise(state.exercise);else{state.playing=true;updateWorkout();updateVrMenu();}}
function vrPause(){state.playing=!state.playing;updateWorkout();updateVrMenu();}
function vrCycle(dir){const ids=vrIndex(),i=ids.indexOf(state.exercise);vrSelect(ids[(i+dir+ids.length)%ids.length]);}
function wireVrButton(id,fn){const el=$(id);if(!el)return;el.addEventListener('click',fn);el.addEventListener('mouseenter',()=>{el.setAttribute('color','#243746')});el.addEventListener('mouseleave',()=>{el.setAttribute('color','#17232d')});}
function setVrPresentation(active){
  const env=document.getElementById('environment');
  const coach=document.getElementById('coach3d');
  if(active){
    // In XR/AR mode the virtual gym is removed so the headset can show its
    // real-world camera passthrough when the browser supports immersive-ar.
    if(env) env.setAttribute('visible',false);
    document.body.classList.add('vr-passthrough-mode');
    if(coach){
      coach.setAttribute('position','-0.78 1.10 -1.65');
      coach.setAttribute('scale','0.92 0.92 0.92');
    }
  }else{
    if(env) env.setAttribute('visible',true);
    document.body.classList.remove('vr-passthrough-mode');
    if(coach){
      coach.setAttribute('position','0 0 -3');
      coach.setAttribute('scale','1 1 1');
    }
  }
}

function initVrUI(){const cam=$('cameraRig').querySelector('a-camera');if(cam){cam.appendChild($('vrMenuRoot'));cam.appendChild($('vrMenuToggle'));}wireVrButton('vrMenuToggle',()=>setVrMenuVisible(!$('vrMenuRoot').getAttribute('visible')));wireVrButton('vrMenuLibrary',()=>{setVrMenuVisible(true);vrSelect('squat');show('detail');});wireVrButton('vrMenuStart',vrStart);wireVrButton('vrMenuPause',vrPause);wireVrButton('vrMenuPrev',()=>vrCycle(-1));wireVrButton('vrMenuNext',()=>vrCycle(1));wireVrButton('vrPickPushup',()=>vrSelect('pushup'));wireVrButton('vrPickRow',()=>vrSelect('row'));wireVrButton('vrPickPlank',()=>vrSelect('plank'));}

$('startBtn').onclick=()=>startExercise('squat');$('libraryBtn').onclick=()=>{buildFilters();renderLibrary();show('library')};$('backHome').onclick=()=>show('home');$('backLibrary').onclick=()=>{buildFilters();renderLibrary();show('library')};$('detailStart').onclick=()=>startExercise();$('detailWorkout').onclick=()=>startExercise();$('playBtn').onclick=()=>{state.playing=true;state.animStart=0;lastCycle=-1};$('pauseBtn').onclick=()=>state.playing=false;$('restartBtn').onclick=()=>{state.animStart=0;state.rep=0;lastCycle=-1};document.querySelectorAll('.speed').forEach(b=>b.onclick=()=>{state.speed=Number(b.dataset.speed);updateWorkout()});document.querySelectorAll('.angle').forEach(b=>b.onclick=()=>{state.angle=b.dataset.angle;updateCoachVisibility()});$('wPlay').onclick=()=>{state.playing=true};$('wPause').onclick=()=>{state.playing=false};$('wComplete').onclick=()=>{state.rep=exercises[state.exercise].reps;updateWorkout();completeSet()};$('wNext').onclick=nextExercise;$('endWorkout').onclick=finishWorkout;$('restartSession').onclick=()=>startExercise('squat');$('summaryLibrary').onclick=()=>{buildFilters();renderLibrary();show('library')};$('summaryHome').onclick=()=>show('home');$('howBtn').onclick=()=>openInfo('How it works','Choose an exercise, study the procedural 3D coach, then start a guided set. On Quest, use the AR button when available for real-world camera passthrough; the virtual gym is hidden and the coach stays front-left. Controllers use laser pointers and triggers for UI selection.');$('settingsBtn').onclick=()=>openInfo('Settings','The prototype uses snap-friendly controller interaction, smooth A-Frame movement, a dark performance-oriented environment and local-only workout state. Browser support for WebXR varies by device.');$('closeModal').onclick=()=>$('infoModal').classList.remove('show');
const scene=$('scene');scene.addEventListener('enter-vr',()=>{setVrPresentation(true);$('vrStatus').textContent='VR active';$('vrMenuToggle').setAttribute('visible',true);setVrMenuVisible(true);toast('AR mode: look slightly down to access workout controls');});scene.addEventListener('exit-vr',()=>{setVrPresentation(false);$('vrStatus').textContent='Browser mode';$('vrMenuToggle').setAttribute('visible',false);setVrMenuVisible(false)});if(!navigator.xr)$('vrStatus').textContent='WebXR unavailable';initVrUI();buildFilters();renderLibrary();openDetail('squat');show('home');
